# Generated by Django 5.0.4 on 2024-04-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat', '0003_connection_active_group_active_groupmember_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
